OBJECT = 20151521.o
SRCS = 20151521.c

CC = gcc
CFLAGS = -g -c -Wall

TARGET = 20151521.out

$(TARGET) : $(OBJECT)
	$(CC) -o $(TARGET) $(OBJECT) -lm 

clean:
	rm -rf $(OBJECT) $(TARGET)
20151521.o: 20151521.c
